### ISSUE TITLE
TypeError with LineString

### ISSUE THREAD

**Issue by AntOlenin** [luscus/geojson.lib.routeboxer#1]
I did everything like this [example](https://www.npmjs.com/package/geojson.lib.routeboxer)

The geojson (LineString) I took from [this](http://geojson.org/geojson-spec.html#id3)

So my code:

`var boxer = new RouteBoxer();`
`var geojson = { "type": "LineString",  "coordinates": [ [100.0, 0.0], [101.0, 1.0] ]}`
`var range = 1;`
`var boxes = boxer.box(geojson, range);`

I got TypeError:

`TypeError: Object 100,0 has no method 'rhumbBearingTo'`

I think that we have to extend the prototype of Array.

We have to add `Array.prototype.rhumbBearingTo` method. I think)

**Comment by luscus** [comment]
I've put a test file. The Route Boxer do work with a route of mine in Europe but still does not work with your example... I will look into it.
